# Generated by Django 4.2.14 on 2025-07-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userprofile_delete_safetyincident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
