# Generated by Django 4.2.14 on 2025-07-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(default='No Hard Hat', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='safety_violations/')),
                ('description', models.TextField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_violations', to='app1.cameraconfiguration')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_violations', to='app1.employee')),
            ],
        ),
    ]
