# Generated by Django 4.2.14 on 2025-07-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_safetyviolation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SafetyViolation',
        ),
    ]
